[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "qml_benchmarks"
description = "A package to benchmark quantum machine learning models"
authors = [{name = "Cha1tanyaa, QML Team XanaduAI"}]
classifiers = [
    "Development Status :: 3 - Extending",
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
    "License :: OSI Approved :: Apache Software License"
]
dependencies = [
    "numpy",
    "pennylane",
    "scikit_learn",
    "matplotlib",
    "jax",
    "jaxlib",
    "flax",
    "optax",
    "typing-extensions",
    "pyyaml",
    "pandas",
    "seaborn",
    "scipy"
]

[project.scripts]
qml-grid-search = "tools.hyperparameter_search.grid_search:main"
qml-score-best = "tools.hyperparameter_search.score_best:main"
qml-orchestrate-search = "tools.benchmarking.orchestrate_search:main"
qml-benchmark-classification = "tools.benchmarking.run_classification:main"
qml-benchmark-regression = "tools.benchmarking.run_regression:main"
qml-generate-extension-datasets = "tools.data_generation.generate_extension_datasets:cli"

